# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuicast" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "37fb8f33b707ab9a30e3785d41542ce532118459fbcd912f78be3580e4b3d496"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_darwin_arm64.tar.gz"
      rename "tuicast_0.1.0_darwin_arm64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.1.0_darwin_arm64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.1.0_darwin_arm64/reference-tui", "reference-tui"
    end
    on_intel do
      sha256 "fc30540a14fa78a56789ad398abeaee66edac02390bd9b80bf023d58d8cd88fc"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_darwin_amd64.tar.gz"
      rename "tuicast_0.1.0_darwin_amd64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.1.0_darwin_amd64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.1.0_darwin_amd64/reference-tui", "reference-tui"
    end
  end
  on_linux do
    on_arm do
      sha256 "d18f1d47039edf4586c551252a11e442405983c37c558c35847d8c55feaf30ef"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_linux_arm64.tar.gz"
      rename "tuicast_0.1.0_linux_arm64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.1.0_linux_arm64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.1.0_linux_arm64/reference-tui", "reference-tui"
    end
    on_intel do
      sha256 "5b2ad4ee33330bb8e451059203ee46e4a23a5ab07e573e7c8848c4b625729a6c"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_linux_amd64.tar.gz"
      rename "tuicast_0.1.0_linux_amd64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.1.0_linux_amd64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.1.0_linux_amd64/reference-tui", "reference-tui"
    end
  end

  name "tuicast"
  desc "Terminal session management and automation for testing text user interfaces."
  homepage "https://github.com/castingcode/tuicast"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuicast-driver"
  binary "tuicast-mcp"
  binary "reference-tui"

  # No zap stanza required
end
