# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuicast" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "c42e881a0b8660e5cf0c3c9ca80732d629de53f588c14bf8d2497a67f59c9d48"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_darwin_arm64.tar.gz"
      rename "tuicast_0.0.2_darwin_arm64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.0.2_darwin_arm64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.0.2_darwin_arm64/reference-tui", "reference-tui"
    end
    on_intel do
      sha256 "9792f3fd6ddbb9ec358eb5103cb1239281d0e286bb26e888474b151e6f10f0dc"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_darwin_amd64.tar.gz"
      rename "tuicast_0.0.2_darwin_amd64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.0.2_darwin_amd64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.0.2_darwin_amd64/reference-tui", "reference-tui"
    end
  end
  on_linux do
    on_arm do
      sha256 "386a41ecfc01d96bc173cdfb6a157db551612619ea0b1da0c5684acfa5c2a6a9"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_linux_arm64.tar.gz"
      rename "tuicast_0.0.2_linux_arm64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.0.2_linux_arm64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.0.2_linux_arm64/reference-tui", "reference-tui"
    end
    on_intel do
      sha256 "8386f621d97a1271cb76079852d76910b0926eefd72db98911640c202afcdfd2"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_linux_amd64.tar.gz"
      rename "tuicast_0.0.2_linux_amd64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.0.2_linux_amd64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.0.2_linux_amd64/reference-tui", "reference-tui"
    end
  end

  name "tuicast"
  desc "Terminal session management and automation for testing text user interfaces."
  homepage "https://github.com/castingcode/tuicast"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuicast-driver"
  binary "tuicast-mcp"
  binary "reference-tui"

  # No zap stanza required
end
