# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuicast" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "221ddacc87eb70815475835bea6aa6305263d402887c4802c111cdacd64605f4"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_darwin_arm64.tar.gz"
      rename "tuicast_0.0.3_darwin_arm64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.0.3_darwin_arm64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.0.3_darwin_arm64/reference-tui", "reference-tui"
    end
    on_intel do
      sha256 "f60f3c8cf353d0e091aace9a86434423f2edc6c106dc8d85dfbc7e0b56df1329"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_darwin_amd64.tar.gz"
      rename "tuicast_0.0.3_darwin_amd64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.0.3_darwin_amd64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.0.3_darwin_amd64/reference-tui", "reference-tui"
    end
  end
  on_linux do
    on_arm do
      sha256 "2cb5898d5d61354d0364870a321838db1b144fc28d796e15788f0d17d5ce660a"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_linux_arm64.tar.gz"
      rename "tuicast_0.0.3_linux_arm64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.0.3_linux_arm64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.0.3_linux_arm64/reference-tui", "reference-tui"
    end
    on_intel do
      sha256 "afecd8dcc02f176dd1f03ddddc1a4efc5945b7a828b8cf28277543868cb022c1"
      url "https://github.com/castingcode/tuicast/releases/download/v#{version}/tuicast_#{version}_linux_amd64.tar.gz"
      rename "tuicast_0.0.3_linux_amd64/tuicast-driver", "tuicast-driver"
      rename "tuicast_0.0.3_linux_amd64/tuicast-mcp", "tuicast-mcp"
      rename "tuicast_0.0.3_linux_amd64/reference-tui", "reference-tui"
    end
  end

  name "tuicast"
  desc "Terminal session management and automation for testing text user interfaces."
  homepage "https://github.com/castingcode/tuicast"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuicast-driver"
  binary "tuicast-mcp"
  binary "reference-tui"

  # No zap stanza required
end
